[package]
name = "terminal_spectrograph"
version = "1.0.0"
authors = ["Allen Welkie <allen.welkie@gmail.com>"]

[[bin]]
name = "tspec"

[dependencies]
rustfft = "2.1.0"
libc = "^0.2"
rustty = "^0.1.9"
docopt = "^0.6"
rustc-serialize = "^0.3"
itertools = "^0.4"
