[package]
name = "terminal_waterfall"
version = "0.1.0"
authors = ["Allen Welkie <>"]

[dependencies]
rustfft = "*"
libc = "*"
num = "*"
rustty = "*"

[dependencies.drawille]
git = "git://github.com/P1start/drawille-rs"
