[package]
name = "terminal_spectrograph"
version = "0.1.0"
authors = ["Allen Welkie <>"]

[dependencies]
rustfft = "*"
libc = "*"
num = "*"
rustty = "*"
docopt = "*"
rustc-serialize = "*"
itertools = "*"
