[package]
name = "terminal_spectrograph"
version = "0.1.0"
authors = ["Allen Welkie <allen.welkie@gmail.com>"]

[[bin]]
name = "tspec"

[dependencies]
rustfft = "*"
libc = "*"
num = "*"
rustty = "*"
docopt = "*"
rustc-serialize = "*"
itertools = "*"
